### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName":"test1",
    "lastName":"user1",
    "email":"test1@gmail.com",
    "password":"test@123",
    "profileImageUrl":"images/test.jpg"
}

### authenticate user / login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"test@123"
}

### read all articles
GET http://localhost:4000/user-api/articles

### user-comment on articles 
POST http://localhost:4000/user-api/articles
Content-Type: application/json

{
    "articleId":"698974280bca24adca771ec9",
    "comment":"excellent blog from the author"
}

### change password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email":"vikas123@gmail.com",
    "currentPassword":"vk@123",
    "newPassword":"vikas@123"
}

### logout
GET http://localhost:4000/common-api/logout